import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect("106.54.211.108", username="ubuntu", password="Zcnhcgd18", timeout=15)
print("Connected")
sftp = ssh.open_sftp()
sftp.put("D:/MySite/blog/frontend/index.html", "/home/ubuntu/blog/frontend/index.html")
sftp.close()
print("Uploaded")
def run(cmd):
    stdin, stdout, stderr = ssh.exec_command(cmd)
    out = stdout.read().decode().strip()
    err = stderr.read().decode().strip()
    if out: print(out)
    if err: print(err)
run("cd ~/blog && docker compose up -d --build frontend 2>&1")
run("curl -s -o /dev/null -w 'HTTP: %{http_code}' http://localhost")
ssh.close()
print("Done")
